export enum PermissionsEnum {

    //High level permissions
    VIEW_ADMIN = 'VIEW_ADMIN',

    // 🔹 Products Module
    VIEW_PRODUCTS = 'VIEW_PRODUCTS',
    ADD_PRODUCT = 'ADD_PRODUCT',
    EDIT_PRODUCT = 'EDIT_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    PRINT_PRODUCTS = 'PRINT_PRODUCTS',

    // 🔹 Users Module
    VIEW_USERS = 'VIEW_USERS',
    ADD_USER = 'ADD_USER',
    EDIT_USER = 'EDIT_USER',
    DELETE_USER = 'DELETE_USER',
    RESET_USER_PASSWORD = 'RESET_USER_PASSWORD',
    ASSIGN_ROLES_TO_USER = 'ASSIGN_ROLES_TO_USER',

    // 🔹 Roles Module
    VIEW_ROLES = 'VIEW_ROLES',
    ADD_ROLE = 'ADD_ROLE',
    EDIT_ROLE = 'EDIT_ROLE',
    DELETE_ROLE = 'DELETE_ROLE',
    ASSIGN_PERMISSIONS_TO_ROLE = 'ASSIGN_PERMISSIONS_TO_ROLE',

    // 🔹 Customers Module
    VIEW_CUSTOMERS = 'VIEW_CUSTOMERS',
    ADD_CUSTOMER = 'ADD_CUSTOMER',
    EDIT_CUSTOMER = 'EDIT_CUSTOMER',
    DELETE_CUSTOMER = 'DELETE_CUSTOMER',
    PRINT_CUSTOMERS = 'PRINT_CUSTOMERS',

    // 🔹 Suppliers Module
    VIEW_SUPPLIERS = 'VIEW_SUPPLIERS',
    ADD_SUPPLIER = 'ADD_SUPPLIER',
    EDIT_SUPPLIER = 'EDIT_SUPPLIER',
    DELETE_SUPPLIER = 'DELETE_SUPPLIER',
    PRINT_SUPPLIERS = 'PRINT_SUPPLIERS',

    // 🔹 Purchase Orders Module
    VIEW_PURCHASE_ORDERS = 'VIEW_PURCHASE_ORDERS',
    ADD_PURCHASE_ORDER = 'ADD_PURCHASE_ORDER',
    EDIT_PURCHASE_ORDER = 'EDIT_PURCHASE_ORDER',
    DELETE_PURCHASE_ORDER = 'DELETE_PURCHASE_ORDER',
    COMPLETE_PURCHASE_ORDER = 'COMPLETE_PURCHASE_ORDER',
    PRINT_PURCHASE_ORDER = 'PRINT_PURCHASE_ORDER',
    APPROVE_PURCHASE_ORDER = 'APPROVE_PURCHASE_ORDER',
    CANCEL_PURCHASE_ORDER = 'CANCEL_PURCHASE_ORDER',

    // 🔹 Sale Orders Module
    VIEW_SALE_ORDERS = 'VIEW_SALE_ORDERS',
    ADD_SALE_ORDER = 'ADD_SALE_ORDER',
    EDIT_SALE_ORDER = 'EDIT_SALE_ORDER',
    DELETE_SALE_ORDER = 'DELETE_SALE_ORDER',
    COMPLETE_SALE_ORDER = 'COMPLETE_SALE_ORDER',
    PRINT_SALE_ORDER = 'PRINT_SALE_ORDER',
    APPROVE_SALE_ORDER = 'APPROVE_SALE_ORDER',
    CANCEL_SALE_ORDER = 'CANCEL_SALE_ORDER',

    // 🔹 Inventory Report Module
    VIEW_INVENTORY_REPORT = 'VIEW_INVENTORY_REPORT',
    PRINT_INVENTORY_REPORT = 'PRINT_INVENTORY_REPORT',

    // 🔹 Activity Logs Module
    VIEW_ACTIVITY_LOGS = 'VIEW_ACTIVITY_LOGS',
    EXPORT_ACTIVITY_LOGS = 'EXPORT_ACTIVITY_LOGS',

    // 🔹 Working Hours Module
    VIEW_WORKING_HOURS = 'VIEW_WORKING_HOURS',
    EDIT_WORKING_HOURS = 'EDIT_WORKING_HOURS',
    MANAGE_WORKING_HOURS_EXCEPTIONS = 'MANAGE_WORKING_HOURS_EXCEPTIONS',
    WORK_OUTSIDE_WORKING_HOURS = 'WORK_OUTSIDE_WORKING_HOURS',

    //To view Company settings
    VIEW_SETTINGS = 'VIEW_SETTINGS',
    EDIT_SETTINGS = 'EDIT_SETTINGS',

    // 🔹 New: Category Module
    VIEW_CATEGORIES = 'VIEW_CATEGORIES',
    ADD_CATEGORY = 'ADD_CATEGORY',
    EDIT_CATEGORY = 'EDIT_CATEGORY',
    DELETE_CATEGORY = 'DELETE_CATEGORY',
    PRINT_CATEGORIES = 'PRINT_CATEGORIES',

    // 🔹 New: Unit Module
    VIEW_UNITS = 'VIEW_UNITS',
    ADD_UNIT = 'ADD_UNIT',
    EDIT_UNIT = 'EDIT_UNIT',
    DELETE_UNIT = 'DELETE_UNIT',
    PRINT_UNITS = 'PRINT_UNITS',

    // 🔹 New: Store Module
    VIEW_STORES = 'VIEW_STORES',
    ADD_STORE = 'ADD_STORE',
    EDIT_STORE = 'EDIT_STORE',
    DELETE_STORE = 'DELETE_STORE',
    PRINT_STORES = 'PRINT_STORES',

    // 🔹 New: Store Transfers Module
    VIEW_STORE_TRANSFERS = 'VIEW_STORE_TRANSFERS',
    ADD_STORE_TRANSFER = 'ADD_STORE_TRANSFER',
    EDIT_STORE_TRANSFER = 'EDIT_STORE_TRANSFER',
    DELETE_STORE_TRANSFER = 'DELETE_STORE_TRANSFER',
    APPROVE_STORE_TRANSFER = 'APPROVE_STORE_TRANSFER',
    PRINT_STORE_TRANSFERS = 'PRINT_STORE_TRANSFERS',

    // 🔹 New: Inventory Management Module
    VIEW_INVENTORY_MANAGEMENT = 'VIEW_INVENTORY_MANAGEMENT',
    MANAGE_INVENTORY = 'MANAGE_INVENTORY',
    ADJUST_INVENTORY = 'ADJUST_INVENTORY',
    VIEW_LOW_STOCK = 'VIEW_LOW_STOCK',

    // 🔹 New: SubCategory Module
    VIEW_SUBCATEGORIES = 'VIEW_SUBCATEGORIES',
    ADD_SUBCATEGORY = 'ADD_SUBCATEGORY',
    EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY',
    DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY',
    PRINT_SUBCATEGORIES = 'PRINT_SUBCATEGORIES',

    EDIT_APPROVED_INVOICE = 'EDIT_APPROVED_INVOICE'
}